services:
    # default configuration for services in this file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # CodeGeneration component services
    Ardenexal\FHIRTools\Component\CodeGeneration\:
        resource: '../../src/Component/CodeGeneration/src/'
        exclude:
            - '../../src/Component/CodeGeneration/src/Attributes/'

    # Specific service configurations for CodeGeneration component
    Ardenexal\FHIRTools\Component\CodeGeneration\Context\BuilderContext:
        public: true

    Ardenexal\FHIRTools\Component\CodeGeneration\Package\PackageLoader:
        public: true

    Ardenexal\FHIRTools\Component\CodeGeneration\Generator\FHIRModelGenerator:
        public: true

    Ardenexal\FHIRTools\Component\CodeGeneration\Generator\FHIRValueSetGenerator:
        public: true