# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Ardenexal\FHIRTools\:
        resource: '../src/'

    # Configure FHIR normalizers to avoid circular dependency with serializer
    # These normalizers should not be injected with the main serializer service
    Ardenexal\FHIRTools\Serialization\FHIRResourceNormalizer:
        arguments:
            $normalizer: null
            $denormalizer: null

    Ardenexal\FHIRTools\Serialization\FHIRBackboneElementNormalizer:
        arguments:
            $normalizer: null
            $denormalizer: null

    Ardenexal\FHIRTools\Serialization\FHIRComplexTypeNormalizer:
        arguments:
            $normalizer: null
            $denormalizer: null

    Ardenexal\FHIRTools\Serialization\FHIRPrimitiveTypeNormalizer:
        arguments:
            $normalizer: null
            $denormalizer: null

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
